# Generated by Django 2.1.2 on 2018-10-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=12)),
                ('working_hours', models.DateTimeField(null=True)),
                ('adress', models.CharField(max_length=450)),
                ('category', models.CharField(max_length=200)),
                ('causin', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('raiting', models.IntegerField(default=0)),
                ('menu', models.TextField()),
                ('event', models.TextField()),
                ('end_point', models.CharField(max_length=120)),
            ],
        ),
    ]
