# Generated by Django 2.1.2 on 2018-10-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='working_hours_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='working_hours_start',
            field=models.TimeField(null=True),
        ),
    ]
